sudo: required
services:
  - docker

before_install:
  - docker build -t taegKim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true taegKim/docker-react npm run test

language: generic 
