sudo: required
services:
  - docker

before_install:
  - docker build -t taegkim6602/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true taegkim6602/docker-react npm run test

language: generic 
