sudo: required
services:
  - docker

before_install:
  - docker build -t taegkim6602/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true taegkim6602/docker-react npm run test

language: generic 

deploy:
  provider: elasticbeanstalk
  resion: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-484694236181"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY